# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: macOS OpenMP
        if: ${{ matrix.os == 'macOS-latest' }}
        run: |
          curl -O https://mac.r-project.org/openmp/openmp-17.0.6-darwin20-Release.tar.gz
          sudo tar fvxz openmp-17.0.6-darwin20-Release.tar.gz -C /
          rm openmp-17.0.6-darwin20-Release.tar.gz
          
      - name: macOS XCode
        if: ${{ matrix.os == 'macOS-latest' }}
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app 
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          echo "xcode is set: $(xcode-select --print-path)"
          echo "using SDK: $(xcrun --show-sdk-version)" 
          
      - name: Dependencies
        run: ./run.sh install_deps

      - name: Test
        run: ./run.sh run_tests
        
      - name: Logs
        run: ./run.sh dump_logs
        if: failure()

      - name: Install
        run: R CMD INSTALL .

      - name: Call
        run: Rscript -e 'ompdetect::ompdetect(); ompdetect::omplimits()'
        
      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: ./run.sh coverage
